#!/usr/bin/ruby -w

radius = 35
symbol_radius = 25
symbol_size = 9

puts "   <!-- Generated by clocknumbers.rb -->"
puts "   <!-- radius=#{radius} symbol_radius=#{symbol_radius} symbol_size=#{symbol_size} -->"
(0..11).each do |n|
  h = n

  a = 2 * Math::PI * (h / 12.0);

  symbol_x = (Math.sin(a) * symbol_radius).round
  symbol_y = -(Math.cos(a) * symbol_radius).round

  puts if h % 3 == 0
  printf(%|   <image id="%dhimage" x="%d" y="%d" width="%d" height="%d" xlink:href="" />\n|,
         h,
         symbol_x - (symbol_size - 1) / 2,
         symbol_y - (symbol_size - 1) / 2,
         symbol_size, symbol_size)

  x = (Math.sin(a) * radius).round
  y = -(Math.cos(a) * radius).round

  printf(%|   <text class="hour" id="%dh" x="%d" y="%d">%d</text>\n|,
         h, x, y, h == 0 ? 12 : h)
end
